### ISSUE TITLE
Set Up Basic React Project

### ISSUE THREAD

**Issue by git-voo** [oss-slu/Step_Time_Biofeedback#4]
**Objective**: Initialize a React project using Create React App and push the project to the repository.

**Steps**:

- [ ] Run npx create-react-app step-tb-frontend.
- [ ] Set up the folder structure and add a README.md explaining how to run the app.
- [ ] Ensure the app runs with npm start and displays a simple "Hello, World!" page.

**Comment by SharmaKabir** [comment]
I've made a PR, can you check it out?
